---
name: "Bug report"
description: "Report a bug with the integration"
labels: "Bug"
body:
- type: markdown
  attributes:
    value: Before you open a new issue, search through the existing issues to see if others have had the same problem.
- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Without steps to reproduce, it will be hard to fix, it is very important that you fill out this part, issues without it will be closed"
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
